### PR TITLE
fix(edit): fix error in latest treesitter

### LINKED ISSUE #32: Error when use command `:Femaco`
I use default configure with setup, but will cause error:
```
Error executing Lua callback: /usr/share/nvim/runtime/lua/vim/treesitter.lua:189: attempt to index local 'node_or_range' (a nil value)
stack traceback:
	/usr/share/nvim/runtime/lua/vim/treesitter.lua:189: in function 'get_match_range'
	...ocal/share/nvim/lazy/nvim-FeMaco.lua/lua/femaco/edit.lua:84: in function 'get_match_at_cursor'
	...ocal/share/nvim/lazy/nvim-FeMaco.lua/lua/femaco/edit.lua:156: in function 'edit_code_block'
	...ocal/share/nvim/lazy/nvim-FeMaco.lua/lua/femaco/init.lua:12: in function <...ocal/share/nvim/lazy/nvim-FeMaco.lua/lua/femaco/init.lua:12>
```

I can confirm:
  - Neovim is the latest nightly version
  - All treesitters are updated

### PR DESCRIPTION
**Pull request by leisiji**
Fix #32 and wrong indentation. Also test OK in old treesitter.

### CODE REVIEW

File: lua/femaco/edit.lua [hunk 1]
```diff
@@ -44,21 +44,28 @@ local get_match_text = function(match, bufnr)
...
-    if language == nil then
-      for lang, val in pairs(match) do
-        return {
-          lang = lang,
-          content_match = val,
-        }
-      end
-    else
+  local language = match.language or match._lang
+  if language == nil then
```
Comment (AckslD) [inline lua/femaco/edit.lua]: [nit] maybe just for cleanness this could be written:
```lua
if language then
  return ...
end
if match.injection then
  return ...
end
for lang, val, .. do
end
```
What do you think?

**Comment by AckslD** [comment]
awesome, thanks! Not sure why the tests fail in CI

File: lua/femaco/edit.lua (hunk 1 above)
Comment (leisiji) [reply lua/femaco/edit.lua]: I think it is an good idea, and I have fixed it.

**Comment by leisiji** [comment]
> awesome, thanks! Not sure why the tests fail in CI

I am finding the reason of tests failing

**Comment by leisiji** [comment]
After checking out nvim-treesitter's CONTRIBUTING.md, I find that @injection.language have been changed to the tsnode type.

File: lua/femaco/edit.lua [hunk 2]
```diff
@@ -90,15 +90,19 @@ local get_match_at_cursor = function()
     local match_data = parse_match(match)
     local content_range = {get_match_range(match_data.content_match)}
     local ranges = {content_range}
+    local lang = match_data.lang
     if match_data.lang_match ~= nil then
       table.insert(ranges, {get_match_range(match_data.lang_match)})
+    elseif type(lang) ~= "string" then
```
Comment (AckslD) [inline lua/femaco/edit.lua:96]: Could this maybe be moved into `parse_match` to not have to deal with the specifics of the various formats `match` can take here?

Comment (AckslD) [reply lua/femaco/edit.lua:96]: Hope you don't mind @leisiji but I did this and merged your fix. Thanks a lot for the help :rocket:

Comment (leisiji) [reply lua/femaco/edit.lua:96]: > Could this maybe be moved into `parse_match` to not have to deal with the specifics of the various formats `match` can take here?

I think that it might be not so easy to put that into `parse_match`, because `_lang` has been moved into injection and the two tables merge into one table. However, `parse_match` only returns one table:

```lua
-- print(vim.inspect(query.get_matches(vim.api.nvim_get_current_buf(), 'injections')))

-- return value of old style
{ {
    _lang = {
      node = <userdata 1>
    },
    injection = {
      content = {
        node = <userdata 2>
      }
    }
  } }

-- current return value, `language` table has been moved into `injection` table 
{ {
    injection = {
      content = {
        node = <userdata 1>
      },
      language = {
        node = <userdata 2>
      }
    }
  } }
```

Comment (AckslD) [reply lua/femaco/edit.lua:96]: I might be missing something but isn't that exactly what we take into account here?
https://github.com/AckslD/nvim-FeMaco.lua/blob/9b1d7cc4a5e773b7fec6318d4981d63bcd5eaf56/lua/femaco/edit.lua#L59

Comment (AckslD) [reply lua/femaco/edit.lua:96]: Should now be handled better in #35
